In [1]:
import tensorflow as tf
import models
from tensorflow.keras.layers import Lambda, Dense, InputLayer, Reshape
from tensorflow.keras.models import Sequential
from utils import iou
import numpy as np

seed = 42
input_shape = (448, 448, 3)
S, B, C = 7, 2, 3

In [2]:
np.random.seed(seed)
x = tf.random.normal((10, *input_shape))
yolo = models.YoloV1(input_shape=input_shape, grid_size=S, num_boxes=2, num_classes=C)
y_pred = yolo(x)

In [3]:
np.random.seed(seed)
y_target = tf.random.normal((10, S, S, 5 + C))

# **Demo class dist. loss**

In [4]:
model = Sequential([
    Dense(7 * 7 * 3),
    Reshape((7, 7, 3))
])

In [5]:
np.random.seed(42)
x = np.random.normal(size=(2, 10))
np.random.seed(42)
target = np.random.normal(size=(2, 7, 7, 3))
#output = model(x)

In [6]:
with tf.GradientTape() as tape:
    output = model(x)
    
    err = target - output
    sqr_err = tf.square(err)
    sum_err = tf.reduce_sum(sqr_err, axis=-1)
    
    mask = (target > 1).astype(np.float32)
    mask = tf.reduce_sum(mask, axis=-1)
    
    loss = tf.reduce_sum((sum_err * mask))
    
[dw_dL, db_dL] = tape.gradient(loss, model.trainable_variables)

In [7]:
loss

<tf.Tensor: shape=(), dtype=float32, numpy=208.70157>

In [11]:
dw_dL[0]

<tf.Tensor: shape=(147,), dtype=float32, numpy=
array([ 0.        ,  0.        ,  0.        , -1.6864551 , -0.3555583 ,
        0.18620792, -2.073008  , -0.80940145,  0.72315085,  1.4507877 ,
        1.2334487 , -1.3799481 ,  0.        ,  0.        ,  0.        ,
        1.2877387 , -0.64275694,  0.6712321 ,  0.8939582 ,  2.737662  ,
        0.36885446,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        3.2702227 , -3.3465273 ,  4.555057  ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        1.1048365 ,  0.13467933, -1.0378306 ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        , -0.9072291 ,
       -0.33104014,  1.7606881 ,  0.        ,  0.        ,  0.        ,
        0.49192   ,  0.7697021 ,  3.0613167 ,  2.287197  ,  0.6037471 ,
       -0.405739